### ISSUE TITLE
block placements delay and more issues

### ISSUE THREAD

**Issue by oClown** [ScribbleLP/MC-TASTools#5]
im having issues when i set the tickrate to under "5" such as blocks placing after i right click and when i click on blocks in my inventory it is delayed too. is there a fix?

**Comment by ScribbleLP** [comment]
That is unfortunately vanilla itself that does this... Inputs and inventory stuff are based on tickrate. Furthermore, mouse inputs are buffered, means if you click 3 times in a tick, minecraft tries to execute it 3 times at the end of the tick and other inputs get eaten... the key to this is to only click once during the tick, wait until the tick is over, then you can click again, without buffering too much...  
  
If you check out [this](https://github.com/MCPfannkuchenYT/LoTAS) mod, in the main menu you will find a button with configuration. And in there, if you enable showTickindicator, a red dot will blink in the top right corner, indicating when a tick passed, so you can time this properly...

**Comment by oClown** [comment]
oh okay.
