### ISSUE TITLE
Game won't load when using VoxelMap

### ISSUE THREAD

**Issue by superJK92iscool** [ScribbleLP/MC-TASTools#6]
Game won't load when using VoxelMap

**Comment by ScribbleTAS** [comment]
1. This mod is very old and unsupported, consider using [LoTAS](https://github.com/MCPfannkuchenYT/LoTAS). 99% of the features in TASTools are present in LoTAS and much more  
2. Looking at voxelmap on curseforge, it looks like there is only one 1.12.2 forge version available that might be compatible with TASTools... there are no Fabric or Liteloader versions of TASTools... So what mc version are you using?
